CREATE TABLE CUSTINFO(
	OCCUPATION VARCHAR(100) NULL,
	AGE INTEGER NULL,
	LASTNAME VARCHAR(100) NULL,
	FIRSTNAME VARCHAR(100) NULL,
	NATIONALID VARCHAR(100) NULL
);
		 
CREATE TABLE HOUSEINFO (
	NATIONALID VARCHAR(100) NULL,
	ADDRESS VARCHAR(100) NULL,
	BEDROOM INTEGER NULL, 
	BATHROOM INTEGER NULL,
	LANDSIZE INTEGER NULL,
	APPRAISEDVALUE INTEGER NULL
);
